let gameseq = [];// this array is used to store the random color generated by computer
let userseq = [];// this array is used to store the color clicked by user

let btns = ["yellow", "red", "blue", "green"];// this array is used to store the color of the button

let started = false;// this variable is used to check whether the game is started or not
let level = 0;// this variable is used to store the level of the game


let h2 = document.querySelector("h2");// this variable is used to store the h2 element

// this function is used to start the game when user press any key 
document.addEventListener("keypress", function() {
    if(
        started === false
    ){
        console.log("game started");
        started = true;

        levelup();
    }

    });
// this function is used to flash the button when computer generate the random color
    function gameFlash(btn){
        btn.classList.add("flash");
        setTimeout(function(){
            btn.classList.remove("flash");
        }, 100);
    }
// this function is used to flash the button when user click on the button
    function userFlash(btn){
        btn.classList.add("userflash");
        setTimeout(function(){
            btn.classList.remove("userflash");
        }, 100);
    }

// this function create to level up and generate random color and push it to gameseq array
    function levelup() {
        userseq = [];
level++;
h2.innerText = `Level ${level} `;

       let randIdx = Math.floor(Math.random() * 4);
        let randColor = btns[randIdx];
        
        let randBtn = document.querySelector(`.${randColor}`);
       // console.log(randBtn);
        //console.log(randColor);
        //console.log(randIdx);
        gameseq.push(randColor);
        console.log(gameseq);
    gameFlash(randBtn);
    }
//checking the answer is correct or not given by user

let h3 = document.querySelector("h3");
highestScore = 0;
    function checkAnswer(idx)  {
    console.log("current level is " , level);

    if(userseq[idx] === gameseq[idx]){
        if(userseq.length === gameseq.length)
            {
           setTimeout(levelup, 1000);
        }
    }
    else{
         if(level > highestScore){  // this condition is used to check whether the current level is greater than highest score or not
            highestScore = level; // this line is used to update the highest score
            h3.innerText = `High Score: ${highestScore}`;// this line is used to update the high score in h3 element
        }
        h2.innerHTML = `Game Over, Your Score was <b>${level}</b>. <br>Press Any Key to Restart`;
        document.querySelector("body").style.backgroundColor = "red";
        setTimeout(function(){
            document.querySelector("body").style.backgroundColor = "white";
        }, 150);
        restartGame();
    }
}
//this function is used to get the id of the button clicked by user and push it to userseq array
    function btnpress() {
        //console.log(this);
        let btn = this;
        userFlash(btn);


        userColor = btn.getAttribute("id");
        console.log(userColor);
        userseq.push(userColor);

        checkAnswer(userseq.length - 1); 
    }

// this function is used to add event listener to all the buttons

    let allBtns = document.querySelectorAll(".btn");
    for(btn of allBtns){
        btn.addEventListener("click", btnpress);}


function restartGame() {
    level = 0;
    gameseq = [];
    userseq = [];
    started = false;
}